--- 
    # - name: "extract artifact"
    #   unarchive:
    #     src: "/home/circleci/project/artifact.tar.gz"
    #     dest: "/home/ubuntu"
    #     remote_src: yes

    # - name: "update apt packages."
    #   become: true
    #   apt:
    #     update_cache: yes

    # - name: "upgrade packages"
    #   become: true
    #   apt:
    #     upgrade: yesls
    
    # - name: "install dependencies."
    #   become: true
    #   apt:
    #     name: ["nodejs", "npm"]
    #     state: latest
    #     update_cache: yes
    
    # - name: "install pm2"
    #   become: true
    #   npm:
    #     name: pm2
    #     global: yes
    #     production: yes
    #     state: present

    - name: Creates directory
      file:
        path: /home/ubuntu/backend
        state: directory
        
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /home/circleci/project/artifact.tar.gz
        dest: /home/ubuntu/backend/
        mode: '664'
  
    - name: extract file
      ansible.builtin.shell:
        chdir: /home/ubuntu/backend/ 
        cmd: tar -xvzf /home/ubuntu/backend/artifact.tar.gz
    
    - name: Start PM2
      ansible.builtin.shell:
        chdir: /home/ubuntu/backend
        cmd: pm2 start npm -- start