--- 
    - name: "extract artifact"
      unarchive:
        src: artifact.tar.gz
        dest: /home/ubuntu
        remote_src: yes

    - name: "Run pm2"
      ansible.builtin.shell: |
        npm install
        pm2 stop default
        pm2 start npm -- start