--- 
    # - name: "extract artifact"
    #   unarchive:
    #     src: "/home/circleci/project/artifact.tar.gz"
    #     dest: "/home/ubuntu"
    #     remote_src: yes

    # - name: "update apt packages."
    #   become: true
    #   apt:
    #     update_cache: yes

    # - name: "upgrade packages"
    #   become: true
    #   apt:
    #     upgrade: yesls
    
    # - name: "install dependencies."
    #   become: true
    #   apt:
    #     name: ["nodejs", "npm"]
    #     state: latest
    #     update_cache: yes
    
    # - name: "install pm2"
    #   become: true
    #   npm:
    #     name: pm2
    #     global: yes
    #     production: yes
    #     state: present

    - name: Creates directory
      file:
        path: /home/ubuntu/backend
        state: directory
        
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /home/circleci/project/artifact.tar.gz
        dest: /home/ubuntu/backend/
        mode: '664'
  
    - name: extract file
      ansible.builtin.shell:
        chdir: /home/ubuntu/backend/ 
        cmd: tar -xvzf /home/ubuntu/backend/artifact.tar.gz
    
    - name: add block to bashrc
      ansible.builtin.blockinfile:
          path: /home/ubuntu/.bashrc
          block: |
            export TYPEORM_CONNECTION="{{ lookup('env', 'TYPEORM_CONNECTION')}}"  
            export TYPEORM_ENTITIES="{{ lookup('env', 'TYPEORM_ENTITIES')}}"
            export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST')}}"
            export TYPEORM_PORT=5432
            export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME')}}"
            export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD')}}"
            export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE')}}"
            export TYPEORM_MIGRATIONS="{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
            export TYPEORM_MIGRATIONS_DIR="{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"
          state: present
          create: true

    - name: Start PM2
      ansible.builtin.shell:
        chdir: /home/ubuntu/backend
        cmd: npm start